import mongoose from "mongoose";
import dotenv from "dotenv";
import dns from "dns";

// Force Google DNS to resolve MongoDB Atlas SRV records properly
dns.setServers(["8.8.8.8", "8.8.4.4"]);
import User from "../models/User.js";
import Product from "../models/Product.js";
import Review from "../models/Review.js";

dotenv.config();

const img = (id, w = 400) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&q=80&auto=format&fit=crop`;

const DEFAULT_USERS = [
  {
    id: "u1",
    name: "Nguyễn Văn Admin",
    email: "admin@glowskin.com",
    password: "admin123",
    role: "admin",
    membership: "VIP",
  },
  {
    id: "u2",
    name: "Nguyễn Khánh Nhi",
    email: "user@glowskin.com",
    password: "user123",
    role: "user",
    membership: "Free",
  },
];

// 20 High-Quality Skincare Cosmetic Unsplash Photo IDs (Clean bottles, jars, and tubes only)
const UNSPLASH_IDS = [
  "1598440947619-2c35fc9aa908", // Clean white bottle
  "1608248597279-f99d160bfcbc", // White jar
  "1601049541289-9b1b7bbbfe19", // White tube
  "1608571423902-eed4a5ad8108", // Dropper bottle
  "1620916566398-39f1143ab7be", // Yellow jar
  "1571781926291-c477ebfd024b", // Orange serum
  "1612817288484-6f916006741a", // Cosmetic tubes
  "1616394584738-fc6e612e71b9", // Amber pump bottle
  "1601049541571-b5ebd0bfdf02", // Cream jar
  "1615397349754-cfa2066a298e", // Skincare serum
  "1601924994987-69e26d50dc26", // Clear oil bottle
  "1594125350300-8f77235aef2b", // Cosmetic lotion
  "1615396895314-b9f1d003a2c5", // White pump bottle
  "1614859324967-bdf461fdb76e", // Gold dropper bottle
  "1611080626919-7cf5a9dbab5b", // Skincare cream box
  "1512290923902-8a9f81dc236c", // Clear dropper bottle
  "1526947425960-945c6e72858f", // Clean tube cream
  "1614859132170-07bf12f45ecb", // Cosmetic tube
  "1614859727914-52fb8f3f8832", // Glass dropper
  "1590439471364-192aa70c0c53"  // Cream bottle
];

const getUnsplashImage = (index, isHover = false) => {
  const finalIdx = (index + (isHover ? 5 : 0)) % UNSPLASH_IDS.length;
  return img(UNSPLASH_IDS[finalIdx]);
};

const DEFAULT_PRODUCTS = [
  // Row 1 (Mix of 4 brands)
  {
    id: "tfs-sun-cream",
    name: "Kem Chống Nắng Chống Bụi Mịn Ánh Sáng Xanh Natural Sun Eco Super Perfect Sun Cream Ex Spf50+ Pa++++",
    brand: "THE FACE SHOP",
    category: "sunscreen",
    price: 359000,
    rating: 5.0,
    reviews: 1,
    skinTypes: ["dry", "normal", "sensitive", "combination"],
    concerns: ["dehydration", "pores", "aging"],
    ingredients: ["Sunflower Seed Oil", "Panthenol", "Adenosine"],
    image: getUnsplashImage(0, false),
    hoverImage: getUnsplashImage(0, true),
    description: "Kem chống nắng bảo vệ da khỏi tia cực tím UV, ánh sáng xanh và ngăn ngừa bụi mịn hiệu quả.",
    stock: 50,
  },
  {
    id: "goodal-vit-c",
    name: "Tinh Chất Dưỡng Sáng Da Mờ Thâm Quýt Xanh Green Tangerine Vitamin C Dark Spot Serum",
    brand: "CLUB CLIO",
    category: "serum",
    price: 749000,
    rating: 4.8,
    reviews: 2,
    skinTypes: ["normal", "dry", "combination", "oily"],
    concerns: ["dark_spots", "dullness", "aging"],
    ingredients: ["Green Tangerine Extract 70%", "Niacinamide", "Vitamin C", "Arbutin"],
    image: getUnsplashImage(1, false),
    hoverImage: getUnsplashImage(1, true),
    description: "Tinh chất quýt xanh chứa hàm lượng Vitamin C tự nhiên đậm đặc giúp làm mờ vết thâm sạm và sáng da sau 2 tuần.",
    stock: 25,
  },
  {
    id: "cetaphil-gentle",
    name: "Sữa Rửa Mặt Dịu Lành Cho Da Nhạy Cảm Gentle Skin Cleanser",
    brand: "Cetaphil",
    category: "cleanser",
    price: 310000,
    rating: 4.9,
    reviews: 1,
    skinTypes: ["sensitive", "dry", "normal"],
    concerns: ["dehydration"],
    ingredients: ["Glycerin", "Niacinamide", "Panthenol"],
    image: getUnsplashImage(2, false),
    hoverImage: getUnsplashImage(2, true),
    description: "Sữa rửa mặt dịu lành được chuyên gia khuyên dùng cho da nhạy cảm, giúp làm sạch sâu mà vẫn dưỡng ẩm.",
    stock: 80,
  },
  {
    id: "lrp-baume-b5",
    name: "Kem Dưỡng Phục Hồi Làm Dịu Kích Ứng Da Cicaplast Baume B5+",
    brand: "La Roche-Posay",
    category: "moisturizer",
    price: 415000,
    rating: 4.9,
    reviews: 1,
    skinTypes: ["sensitive", "dry", "combination", "normal"],
    concerns: ["dehydration", "acne"],
    ingredients: ["Panthenol 5%", "Madecassoside", "Tribioma"],
    image: getUnsplashImage(3, false),
    hoverImage: getUnsplashImage(3, true),
    description: "Kem dưỡng phục hồi đa công dụng giúp làm dịu da kích ứng, mẩn đỏ và bảo vệ hàng rào bảo vệ da.",
    stock: 60,
  },

  // Cleansers
  {
    id: "tfs-nose-strips",
    name: "Sữa Rửa Mặt Làm Sạch Lỗ Chân Lông Jeju Volcanic Lava Pore Cleansing Foam",
    brand: "THE FACE SHOP",
    category: "cleanser",
    price: 199000,
    rating: 5.0,
    reviews: 1,
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "pores"],
    ingredients: ["Jeju Volcanic Ash", "Aloe Extract", "Lotus Flower Extract"],
    image: getUnsplashImage(4, false),
    hoverImage: getUnsplashImage(4, true),
    description: "Sữa rửa mặt tro núi lửa Jeju giúp hút sạch dầu thừa, se khít lỗ chân lông và làm sạch mụn đầu đen.",
    stock: 45,
  },
  {
    id: "tfs-herb-day",
    name: "Sữa Rửa Mặt Tạo Bọt Chiết Xuất Nha Đam Herb Day 365 Aloe & Green Tea Cleansing Foam",
    brand: "THE FACE SHOP",
    category: "cleanser",
    price: 359000,
    rating: 5.0,
    reviews: 1,
    skinTypes: ["sensitive", "dry", "normal", "combination"],
    concerns: ["dehydration", "dullness"],
    ingredients: ["Aloe Vera Extract", "Green Tea Extract", "Coconut Acid"],
    image: getUnsplashImage(5, false),
    hoverImage: getUnsplashImage(5, true),
    description: "Sữa rửa mặt thảo mộc dịu nhẹ, làm dịu da nhạy cảm và duy trì độ ẩm tự nhiên.",
    stock: 0,
  },
  {
    id: "cerave-sa-cleanser",
    name: "Sữa Rửa Mặt Cho Da Dầu Mụn SA Smoothing Cleanser",
    brand: "CeraVe",
    category: "cleanser",
    price: 389000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "pores"],
    ingredients: ["Salicylic Acid", "Ceramides", "Hyaluronic Acid"],
    image: getUnsplashImage(6, false),
    hoverImage: getUnsplashImage(6, true),
    description: "Sữa rửa mặt chứa BHA giúp tẩy tế bào chết nhẹ nhàng, ngừa mụn và củng cố màng bảo vệ da.",
    stock: 50,
  },
  {
    id: "cosrx-salicylic",
    name: "Sữa Rửa Mặt Ngừa Mụn Chiết Xuất Tràm Trà Salicylic Acid Daily Gentle Cleanser",
    brand: "COSRX",
    category: "cleanser",
    price: 249000,
    rating: 4.7,
    reviews: 0,
    skinTypes: ["oily", "combination", "sensitive"],
    concerns: ["acne", "pores"],
    ingredients: ["Salicylic Acid 0.5%", "Tea Tree Oil", "Willow Bark Water"],
    image: getUnsplashImage(7, false),
    hoverImage: getUnsplashImage(7, true),
    description: "Sữa rửa mặt làm sạch bã nhờn, thông thoáng lỗ chân lông và làm dịu nốt mụn sưng viêm.",
    stock: 65,
  },
  {
    id: "vichy-normaderm",
    name: "Sữa Rửa Mặt Dạng Gel Cho Da Dầu Mụn Normaderm Phytosolution Gel",
    brand: "Vichy",
    category: "cleanser",
    price: 495000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "pores"],
    ingredients: ["Zinc", "Copper", "Salicylic Acid", "Vichy Mineralizing Water"],
    image: getUnsplashImage(8, false),
    hoverImage: getUnsplashImage(8, true),
    description: "Gel rửa mặt làm sạch sâu, kiềm dầu hiệu quả và phục hồi làn da mụn nhạy cảm.",
    stock: 40,
  },
  {
    id: "innisfree-bija-cleanser",
    name: "Sữa Rửa Mặt Ngừa Mụn Bija Trouble Facial Foam",
    brand: "Innisfree",
    category: "cleanser",
    price: 260000,
    rating: 4.6,
    reviews: 0,
    skinTypes: ["oily", "sensitive", "combination"],
    concerns: ["acne"],
    ingredients: ["Bija Oil", "Salicylic Acid", "Green Tea Extract"],
    image: getUnsplashImage(9, false),
    hoverImage: getUnsplashImage(9, true),
    description: "Sữa rửa mặt chiết xuất từ quả Bija giúp bảo vệ da mụn, kháng viêm và làm sạch dịu lành.",
    stock: 55,
  },
  {
    id: "tfs-dr-belmeur",
    name: "Sữa Rửa Mặt Cân Bằng pH Dr.Belmeur Daily Repair Foam Cleanser",
    brand: "THE FACE SHOP",
    category: "cleanser",
    price: 399000,
    rating: 4.7,
    reviews: 0,
    skinTypes: ["sensitive", "dry", "normal"],
    concerns: ["dehydration"],
    ingredients: ["Phytosphingosine", "Moroheiya Extract", "Birch Sap"],
    image: getUnsplashImage(10, false),
    hoverImage: getUnsplashImage(10, true),
    description: "Sữa rửa mặt dạng gel tạo bọt dịu nhẹ, độ pH tối ưu giúp làm dịu và bảo vệ da nhạy cảm.",
    stock: 35,
  },
  {
    id: "cerave-hydrating-cleanser",
    name: "Sữa Rửa Mặt Cấp Ẩm Cho Da Khô Hydrating Cleanser",
    brand: "CeraVe",
    category: "cleanser",
    price: 379000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dehydration"],
    ingredients: ["Ceramides 1, 3, 6-II", "Hyaluronic Acid", "Glycerin"],
    image: getUnsplashImage(11, false),
    hoverImage: getUnsplashImage(11, true),
    description: "Sữa rửa mặt không tạo bọt giúp làm sạch nhẹ nhàng mà vẫn giữ ẩm lâu dài cho da khô.",
    stock: 70,
  },

  // Toners
  {
    id: "klairs-supple-toner",
    name: "Nước Hoa Hồng Cấp Ẩm Làm Dịu Da Supple Preparation Facial Toner",
    brand: "Dear Klairs",
    category: "toner",
    price: 365000,
    rating: 4.9,
    reviews: 0,
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["dehydration"],
    ingredients: ["Phyto-Oligo", "Beta-Glucan", "Centella Asiatica Extract"],
    image: getUnsplashImage(12, false),
    hoverImage: getUnsplashImage(12, true),
    description: "Nước cân bằng giúp cấp nước sâu, làm mềm mịn da và cân bằng độ pH tự nhiên.",
    stock: 60,
  },
  {
    id: "somebymi-aha-bha",
    name: "Nước Hoa Hồng Ngừa Mụn AHA-BHA-PHA 30 Days Miracle Toner",
    brand: "Some By Mi",
    category: "toner",
    price: 349000,
    rating: 4.7,
    reviews: 0,
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["acne", "pores", "dullness"],
    ingredients: ["Real Tea Tree 10,000ppm", "AHA", "BHA", "PHA", "Niacinamide"],
    image: getUnsplashImage(13, false),
    hoverImage: getUnsplashImage(13, true),
    description: "Nước cân bằng loại bỏ tế bào chết, sạch bã nhờn, làm thông thoáng lỗ chân lông và giảm mụn chỉ sau 30 ngày.",
    stock: 50,
  },
  {
    id: "cosrx-aha-bha-toner",
    name: "Nước Hoa Hồng Tẩy Tế Bào Chết AHA/BHA Clarifying Treatment Toner",
    brand: "COSRX",
    category: "toner",
    price: 289000,
    rating: 4.6,
    reviews: 0,
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["pores", "dullness"],
    ingredients: ["Willow Bark Water", "Apple Fruit Water", "Glycolic Acid", "Betaine Salicylate"],
    image: getUnsplashImage(14, false),
    hoverImage: getUnsplashImage(14, true),
    description: "Nước hoa hồng xịt tiện lợi giúp tẩy da chết nhẹ nhàng, duy trì làn da mịn màng và tươi sáng.",
    stock: 55,
  },
  {
    id: "ordinary-glycolic-toner",
    name: "Nước Hoa Hồng Tẩy Da Chết Sáng Da Glycolic Acid 7% Toning Solution",
    brand: "The Ordinary",
    category: "toner",
    price: 395000,
    rating: 4.6,
    reviews: 0,
    skinTypes: ["normal", "oily", "combination"],
    concerns: ["dullness", "dark_spots"],
    ingredients: ["Glycolic Acid 7%", "Ginseng Root Extract", "Aloe Vera", "Tasmanian Pepperberry"],
    image: getUnsplashImage(15, false),
    hoverImage: getUnsplashImage(15, true),
    description: "Toner tẩy da chết hóa học AHA giúp tái tạo bề mặt da, làm đều màu da và tăng độ bóng mượt.",
    stock: 30,
  },
  {
    id: "estee-micro-essence",
    name: "Nước Thần Phục Hồi Dưỡng Sáng Da Micro Essence Activating Treatment Lotion",
    brand: "Estee Lauder",
    category: "toner",
    price: 1850000,
    rating: 4.9,
    reviews: 0,
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["aging", "dehydration", "dullness"],
    ingredients: ["Bifida Ferment Lysate", "Yeast Extract", "Tripeptide-32", "Sodium Hyaluronate"],
    image: getUnsplashImage(16, false),
    hoverImage: getUnsplashImage(16, true),
    description: "Nước thần chứa dưỡng chất lên men cô đặc giúp nuôi dưỡng sâu, tăng cường đàn hồi và trẻ hóa làn da.",
    stock: 20,
  },
  {
    id: "laneige-cream-skin",
    name: "Nước Cân Bằng Dưỡng Ẩm Dạng Sữa Cream Skin Cerapeptide Refiner",
    brand: "Laneige",
    category: "toner",
    price: 680000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dehydration"],
    ingredients: ["Cerapeptide", "White Leaf Tea Water", "Meadowfoam Seed Oil"],
    image: getUnsplashImage(17, false),
    hoverImage: getUnsplashImage(17, true),
    description: "Nước hoa hồng dạng sữa độc đáo kết hợp nước cân bằng và kem dưỡng ẩm giúp tăng khả năng giữ ẩm sâu cho da khô.",
    stock: 35,
  },
  {
    id: "loreal-revitalift-toner",
    name: "Nước Hoa Hồng Săn Mịn Da Revitalift Aqua Milky Toner",
    brand: "L'Oreal Paris",
    category: "toner",
    price: 249000,
    rating: 4.7,
    reviews: 0,
    skinTypes: ["normal", "dry", "combination"],
    concerns: ["aging", "dehydration"],
    ingredients: ["Retinyl Palmitate", "Centella Asiatica", "Yeast Extract"],
    image: getUnsplashImage(18, false),
    hoverImage: getUnsplashImage(18, true),
    description: "Nước hoa hồng ngăn ngừa lão hóa, làm săn chắc cơ mặt và dưỡng ẩm tối ưu.",
    stock: 45,
  },
  {
    id: "tfs-rice-toner",
    name: "Nước Hoa Hồng Dưỡng Sáng Da Chiết Xuất Gạo Rice & Ceramide Moisturizing Toner",
    brand: "THE FACE SHOP",
    category: "toner",
    price: 189000,
    rating: 4.5,
    reviews: 0,
    skinTypes: ["dry", "normal", "combination"],
    concerns: ["dullness", "dehydration"],
    ingredients: ["Rice Extract", "Ceramide NP", "Lecithin"],
    image: getUnsplashImage(19, false),
    hoverImage: getUnsplashImage(19, true),
    description: "Nước hoa hồng dưỡng ẩm từ gạo giúp nuôi dưỡng làn da xỉn màu trở nên trắng sáng hồng hào.",
    stock: 50,
  },

  // Serums
  {
    id: "cosrx-snail-mucus",
    name: "Tinh Chất Ốc Sên Phục Hồi Tái Tạo Da Advanced Snail 96 Mucin Power Essence",
    brand: "COSRX",
    category: "serum",
    price: 389000,
    rating: 4.9,
    reviews: 0,
    skinTypes: ["dry", "normal", "combination", "sensitive", "oily"],
    concerns: ["dehydration", "aging", "acne"],
    ingredients: ["Snail Secretion Filtrate 96%", "Sodium Hyaluronate", "Allantoin"],
    image: getUnsplashImage(20, false),
    hoverImage: getUnsplashImage(20, true),
    description: "Tinh chất chứa 96% dịch nhầy ốc sên giúp phục hồi làn da tổn thương, cấp ẩm sâu và chống lão hóa hiệu quả.",
    stock: 55,
  },
  {
    id: "innisfree-green-tea",
    name: "Tinh Chất Trà Xanh Cấp Nước Hyaluronic Acid Green Tea Seed Serum",
    brand: "Innisfree",
    category: "serum",
    price: 649000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["dry", "normal", "combination", "oily", "sensitive"],
    concerns: ["dehydration"],
    ingredients: ["Green Tea Seed Oil", "Beauty Green Tea Extract", "5 types of Hyaluronic Acid"],
    image: getUnsplashImage(21, false),
    hoverImage: getUnsplashImage(21, true),
    description: "Tinh chất mầm trà xanh đình đám giúp cấp ẩm cấp nước tức thì, làm da căng mọng bóng mượt.",
    stock: 45,
  },
  {
    id: "vichy-mineral-89",
    name: "Dưỡng Chất Khoáng Cô Đặc Phục Hồi Bảo Vệ Da Mineral 89 Booster",
    brand: "Vichy",
    category: "serum",
    price: 890000,
    rating: 4.9,
    reviews: 0,
    skinTypes: ["dry", "normal", "combination", "oily", "sensitive"],
    concerns: ["dehydration", "aging"],
    ingredients: ["Vichy Volcanic Water 89%", "Hyaluronic Acid 0.4%"],
    image: getUnsplashImage(22, false),
    hoverImage: getUnsplashImage(22, true),
    description: "Dưỡng chất khoáng cô đặc củng cố hàng rào bảo vệ da, ngăn ngừa tổn thương do môi trường bên ngoài.",
    stock: 30,
  },
  {
    id: "estee-anr",
    name: "Tinh Chất Phục Hồi Da Ban Đêm Advanced Night Repair Synchronized Recovery Complex",
    brand: "Estee Lauder",
    category: "serum",
    price: 2490000,
    rating: 5.0,
    reviews: 0,
    skinTypes: ["dry", "normal", "combination", "sensitive", "oily"],
    concerns: ["aging", "dehydration", "dullness"],
    ingredients: ["Bifida Ferment Lysate", "Yeast Extract", "Tripeptide-32", "Sodium Hyaluronate"],
    image: getUnsplashImage(23, false),
    hoverImage: getUnsplashImage(23, true),
    description: "Huyền thoại phục hồi da ban đêm giúp xóa mờ nếp nhăn, tăng cường săn chắc và làm sáng mịn làn da tươi trẻ.",
    stock: 15,
  },
  {
    id: "ordinary-niacinamide",
    name: "Tinh Chất Giảm Mụn Sáng Da Niacinamide 10% + Zinc 1%",
    brand: "The Ordinary",
    category: "serum",
    price: 220000,
    rating: 4.5,
    reviews: 0,
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["acne", "pores", "dark_spots"],
    ingredients: ["Niacinamide 10%", "Zinc PCA 1%", "Tamarindus Indica Seed Gum"],
    image: getUnsplashImage(24, false),
    hoverImage: getUnsplashImage(24, true),
    description: "Tinh chất kiểm soát dầu thừa, se khít lỗ chân lông, hỗ trợ làm dịu nốt mụn sưng và giảm vết thâm sau mụn.",
    stock: 80,
  },
  {
    id: "loreal-glycolic",
    name: "Tinh Chất Dưỡng Sáng Mờ Thâm Nhanh Glycolic-Bright Instant Glowing Serum",
    brand: "L'Oreal Paris",
    category: "serum",
    price: 369000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["normal", "dry", "combination", "oily"],
    concerns: ["dark_spots", "dullness"],
    ingredients: ["Glycolic Acid 1.0%", "Niacinamide", "Vitamin C", "Salicylic Acid"],
    image: getUnsplashImage(25, false),
    hoverImage: getUnsplashImage(25, true),
    description: "Tinh chất chứa 1% AHA giúp tẩy nhẹ tế bào chết bề mặt, giảm vết thâm sạm và mang lại làn da trắng mịn rạng rỡ.",
    stock: 60,
  },
  {
    id: "somebymi-retinol",
    name: "Tinh Chất Trẻ Hóa Tái Tạo Da Nhạy Cảm Retinol Intense Reactivating Serum",
    brand: "Some By Mi",
    category: "serum",
    price: 490000,
    rating: 4.7,
    reviews: 0,
    skinTypes: ["normal", "dry", "combination", "oily", "sensitive"],
    concerns: ["aging", "pores", "dark_spots"],
    ingredients: ["Retinol 0.1%", "Retinal 1ppm", "Bakuchiol 5,000ppm", "Panthenol"],
    image: getUnsplashImage(26, false),
    hoverImage: getUnsplashImage(26, true),
    description: "Tinh chất kết hợp Retinol và Bakuchiol chống lão hóa, se khít lỗ chân lông dịu nhẹ cho cả làn da nhạy cảm.",
    stock: 30,
  },
  {
    id: "somebymi-snail-truecica",
    name: "Serum Phục Hồi Da Sau Mụn Sẹo Rỗ Snail Truecica Miracle Repair Serum",
    brand: "Some By Mi",
    category: "serum",
    price: 389000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["dry", "normal", "combination", "oily", "sensitive"],
    concerns: ["acne", "pores"],
    ingredients: ["Black Snail Extract 89%", "Truecica 10,000ppm", "Centella Extract"],
    image: getUnsplashImage(27, false),
    hoverImage: getUnsplashImage(27, true),
    description: "Serum dịch ốc sên đen và thảo mộc Truecica làm lành vết thương sau mụn, mờ sẹo rỗ và củng cố biểu bì.",
    stock: 45,
  },
  {
    id: "loreal-hyaluronic-acid",
    name: "Serum Cấp Ẩm Siêu Căng Bóng Revitalift Hyaluronic Acid 1.5%",
    brand: "L'Oreal Paris",
    category: "serum",
    price: 459000,
    rating: 4.9,
    reviews: 0,
    skinTypes: ["dry", "normal", "combination", "sensitive", "oily"],
    concerns: ["dehydration", "aging"],
    ingredients: ["Macro HA 0.5%", "Micro HA 1.0%", "Glycerin"],
    image: getUnsplashImage(28, false),
    hoverImage: getUnsplashImage(28, true),
    description: "Serum chứa hàm lượng Hyaluronic Acid kép cao giúp ngậm nước sâu, làm đầy nếp nhăn và mang lại làn da căng bóng mịn màng.",
    stock: 60,
  },
  {
    id: "klairs-vitamin-drop",
    name: "Tinh Chất Vitamin C Dưỡng Sáng Trắng Da Freshly Juiced Vitamin Drop",
    brand: "Dear Klairs",
    category: "serum",
    price: 395000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["normal", "dry", "combination", "sensitive"],
    concerns: ["dark_spots", "dullness"],
    ingredients: ["L-Ascorbic Acid 5%", "Centella Asiatica Extract", "Yuzu Extract"],
    image: getUnsplashImage(29, false),
    hoverImage: getUnsplashImage(29, true),
    description: "Tinh chất Vitamin C tươi dịu nhẹ giúp cải thiện các nốt thâm sạm, da xỉn màu không gây kích ứng.",
    stock: 50,
  },

  // Moisturizers
  {
    id: "klairs-blue-cream",
    name: "Kem Dưỡng Làm Dịu Phục Hồi Da Ban Đêm Midnight Blue Calming Cream",
    brand: "Dear Klairs",
    category: "moisturizer",
    price: 420000,
    rating: 4.9,
    reviews: 0,
    skinTypes: ["sensitive", "oily", "combination", "normal"],
    concerns: ["acne", "dehydration"],
    ingredients: ["Guaiazulene (Chamomile Extract)", "Centella Asiatica", "Ceramide NP"],
    image: getUnsplashImage(30, false),
    hoverImage: getUnsplashImage(30, true),
    description: "Kem dưỡng màu xanh tự nhiên từ hoa cúc làm dịu vết mụn sưng viêm, mẩn đỏ và hạ nhiệt làn da bỏng rát cực tốt.",
    stock: 45,
  },
  {
    id: "laneige-water-bank",
    name: "Kem Dưỡng Ẩm Sâu Cho Da Khô Water Bank Blue Hyaluronic Cream",
    brand: "Laneige",
    category: "moisturizer",
    price: 950000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dehydration", "aging"],
    ingredients: ["Blue Hyaluronic Acid", "Ceramide NP", "Beta-Glucan"],
    image: getUnsplashImage(31, false),
    hoverImage: getUnsplashImage(31, true),
    description: "Kem dưỡng ẩm chuyên sâu với HA siêu nhỏ giúp tái tạo hàng rào dưỡng ẩm tự nhiên cho da khô nứt nẻ.",
    stock: 30,
  },
  {
    id: "cetaphil-moisturizing",
    name: "Kem Dưỡng Ẩm Dành Cho Da Khô Nhạy Cảm Moisturizing Cream",
    brand: "Cetaphil",
    category: "moisturizer",
    price: 299000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["dry", "sensitive", "normal"],
    concerns: ["dehydration"],
    ingredients: ["Sweet Almond Oil", "Glycerin", "Vitamin E"],
    image: getUnsplashImage(32, false),
    hoverImage: getUnsplashImage(32, true),
    description: "Kem dưỡng không chứa hương liệu, chất kem lành tính cung cấp độ ẩm kéo dài và bảo vệ làn da nhạy cảm.",
    stock: 65,
  },
  {
    id: "cerave-pm-lotion",
    name: "Sữa Dưỡng Ẩm Phục Hồi Ban Đêm PM Facial Moisturizing Lotion",
    brand: "CeraVe",
    category: "moisturizer",
    price: 399000,
    rating: 4.7,
    reviews: 0,
    skinTypes: ["normal", "dry", "sensitive", "combination"],
    concerns: ["dehydration"],
    ingredients: ["Niacinamide", "3 Essential Ceramides", "Hyaluronic Acid"],
    image: getUnsplashImage(33, false),
    hoverImage: getUnsplashImage(33, true),
    description: "Sữa dưỡng da đêm dịu mát chứa Niacinamide giúp tái tạo lớp biểu bì bị tổn thương và giữ ẩm.",
    stock: 50,
  },
  {
    id: "klairs-rich-moist",
    name: "Kem Dưỡng Ẩm Cho Da Khô Mất Nước Rich Moist Soothing Cream",
    brand: "Dear Klairs",
    category: "moisturizer",
    price: 389000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dehydration"],
    ingredients: ["Beta-Glucan", "Centella Extract", "Jojoba Seed Oil"],
    image: getUnsplashImage(34, false),
    hoverImage: getUnsplashImage(34, true),
    description: "Kem dưỡng ẩm lành tính cấp nước lâu dài, làm mềm và giảm kích ứng cho làn da thô ráp.",
    stock: 40,
  },
  {
    id: "tfs-chia-seed",
    name: "Kem Dưỡng Cấp Nước Cho Da Dầu Thiếu Nước Chia Seed Hydro Cream",
    brand: "THE FACE SHOP",
    category: "moisturizer",
    price: 529000,
    rating: 4.6,
    reviews: 0,
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["dehydration", "pores"],
    ingredients: ["Chia Seed Extract", "Pink Vitamin (B12)", "Cotton Seed Extract"],
    image: getUnsplashImage(35, false),
    hoverImage: getUnsplashImage(35, true),
    description: "Kem dưỡng dạng gel cấp nước dồi dào từ hạt Chia giúp làn da mượt mà, kiểm soát bã nhờn tối ưu.",
    stock: 25,
  },
  {
    id: "cosrx-centella-cream",
    name: "Kem Dưỡng Rau Má Làm Dịu Mụn Phục Hồi Centella Blemish Cream",
    brand: "COSRX",
    category: "moisturizer",
    price: 360000,
    rating: 4.5,
    reviews: 0,
    skinTypes: ["combination", "oily", "sensitive"],
    concerns: ["acne"],
    ingredients: ["Centella Asiatica Leaf Water 50%", "Zinc Oxide", "Tea Tree Oil"],
    image: getUnsplashImage(36, false),
    hoverImage: getUnsplashImage(36, true),
    description: "Kem dưỡng rau má bôi mụn giúp giảm viêm, gom cồi mụn nhanh và hạn chế vết sẹo thâm trên da.",
    stock: 35,
  },
  {
    id: "somebymi-yuja-gel-cream",
    name: "Gel Dưỡng Sáng Da Mờ Thâm Quýt Yuja Niacin Brightening Moisture Gel Cream",
    brand: "Some By Mi",
    category: "moisturizer",
    price: 320000,
    rating: 4.6,
    reviews: 0,
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["dark_spots", "dullness"],
    ingredients: ["Yuja Extract 90%", "Niacinamide 5%", "Glutathione", "Arbutin"],
    image: getUnsplashImage(37, false),
    hoverImage: getUnsplashImage(37, true),
    description: "Gel dưỡng mỏng mát làm mát tức thời, dưỡng sáng mờ thâm nám nhờ vitamin C dồi dào.",
    stock: 50,
  },

  // Sunscreens
  {
    id: "lrp-anthelios-fluid",
    name: "Kem Chống Nắng Kiểm Soát Dầu Anthelios UVMune 400 Oil Control Fluid Spf50+",
    brand: "La Roche-Posay",
    category: "sunscreen",
    price: 495000,
    rating: 4.9,
    reviews: 0,
    skinTypes: ["oily", "combination"],
    concerns: ["pores", "aging"],
    ingredients: ["Mexoryl 400", "Airlicium", "La Roche-Posay Thermal Water"],
    image: getUnsplashImage(38, false),
    hoverImage: getUnsplashImage(38, true),
    description: "Kem chống nắng dạng sữa mỏng nhẹ bảo vệ màng da tối ưu khỏi tia UVA dài nguy hiểm, kiểm soát bóng nhờn 12h.",
    stock: 75,
  },
  {
    id: "loreal-uv-defender",
    name: "Kem Chống Nắng Kiềm Dầu Mịn Lì UV Defender Serum Protector Matte & Fresh Spf50+",
    brand: "L'Oreal Paris",
    category: "sunscreen",
    price: 279000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["oily", "combination"],
    concerns: ["pores", "aging"],
    ingredients: ["Mexoryl SX/XL", "Airlicium", "Niacinamide"],
    image: getUnsplashImage(39, false),
    hoverImage: getUnsplashImage(39, true),
    description: "Kem chống nắng kiềm dầu cực đỉnh, giữ bề mặt da mịn lì không trôi dưới tác động nắng gắt đô thị.",
    stock: 60,
  },
  {
    id: "cetaphil-sun-fluid",
    name: "Kem Chống Nắng Dịu Nhẹ Cho Da Nhạy Cảm Sun SPF50+ Light Gel",
    brand: "Cetaphil",
    category: "sunscreen",
    price: 450000,
    rating: 4.7,
    reviews: 0,
    skinTypes: ["sensitive", "dry", "normal"],
    concerns: ["dehydration"],
    ingredients: ["Titanium Dioxide", "Glycerin", "Vitamin E"],
    image: getUnsplashImage(40, false),
    hoverImage: getUnsplashImage(40, true),
    description: "Kem chống nắng dạng gel mỏng nhẹ bảo vệ tối đa cho da nhạy cảm trước tia UVA và UVB.",
    stock: 40,
  },
  {
    id: "somebymi-truecica-sun",
    name: "Kem Chống Nắng Làm Dịu Da Mụn Truecica Mineral Calming Tone-up Sunscreen",
    brand: "Some By Mi",
    category: "sunscreen",
    price: 320000,
    rating: 4.7,
    reviews: 0,
    skinTypes: ["oily", "sensitive", "combination"],
    concerns: ["acne", "dullness"],
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Truecica 378,000ppm"],
    image: getUnsplashImage(41, false),
    hoverImage: getUnsplashImage(41, true),
    description: "Kem chống nắng vật lý nâng tone tự nhiên, làm dịu các nốt mụn viêm sưng thích hợp da mụn.",
    stock: 50,
  },
  {
    id: "innisfree-tone-up-sun",
    name: "Kem Chống Nắng Nâng Tone Kiềm Dầu Tone Up No Sebum Sunscreen EX SPF50+",
    brand: "Innisfree",
    category: "sunscreen",
    price: 360000,
    rating: 4.6,
    reviews: 0,
    skinTypes: ["oily", "combination"],
    concerns: ["dullness", "pores"],
    ingredients: ["Zinc Oxide", "Jeju Green Tea", "Centella Extract"],
    image: getUnsplashImage(42, false),
    hoverImage: getUnsplashImage(42, true),
    description: "Kem chống nắng nâng tone trắng hồng xinh xắn kiêm lót trang điểm, bảo vệ da kiềm dầu xuất sắc.",
    stock: 45,
  },

  // Treatments
  {
    id: "loreal-micellar",
    name: "Nước Tẩy Trang Làm Sạch Sâu 3-in-1 Refreshing Micellar Water",
    brand: "L'Oreal Paris",
    category: "treatment",
    price: 229000,
    rating: 4.8,
    reviews: 1,
    skinTypes: ["normal", "oily", "combination"],
    concerns: ["pores", "dehydration"],
    ingredients: ["Micellar Water", "Glycerin", "Hexylene Glycol"],
    image: getUnsplashImage(43, false),
    hoverImage: getUnsplashImage(43, true),
    description: "Nước tẩy trang 3 trong 1 làm sạch sâu, hút sạch bã nhờn, làm tươi mát da mà không cần rửa lại với nước.",
    stock: 70,
  },
  {
    id: "banila-clean-it",
    name: "Sáp Tẩy Trang Làm Sạch Sâu Dịu Nhẹ Clean It Zero Cleansing Balm Original",
    brand: "Banila Co",
    category: "treatment",
    price: 390000,
    rating: 4.9,
    reviews: 0,
    skinTypes: ["dry", "normal", "combination", "oily"],
    concerns: ["pores", "dehydration"],
    ingredients: ["Acerola Fruit Extract", "Active Thermal Water", "Vitamin C"],
    image: getUnsplashImage(44, false),
    hoverImage: getUnsplashImage(44, true),
    description: "Sáp tẩy trang chuyển thể dạng dầu và sữa giúp tẩy sạch mọi lớp trang điểm cứng đầu và kem chống nắng.",
    stock: 40,
  },
  {
    id: "laneige-lip-mask",
    name: "Mặt Nạ Ngủ Cho Môi Cấp Ẩm Trẻ Hóa Lip Sleeping Mask Berry",
    brand: "Laneige",
    category: "treatment",
    price: 450000,
    rating: 4.9,
    reviews: 0,
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dehydration"],
    ingredients: ["Berry Mix Complex", "Vitamin C", "Coconut Oil"],
    image: getUnsplashImage(45, false),
    hoverImage: getUnsplashImage(45, true),
    description: "Mặt nạ ngủ môi huyền thoại hương dâu tây nhẹ nhàng cấp ẩm sâu, loại bỏ tế bào chết làm đôi môi căng hồng.",
    stock: 60,
  },
  {
    id: "innisfree-volcanic-clay",
    name: "Mặt Nạ Đất Sét Tro Núi Lửa Super Volcanic Pore Clay Mask 2X",
    brand: "Innisfree",
    category: "treatment",
    price: 340000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["oily", "combination"],
    concerns: ["pores", "acne"],
    ingredients: ["Jeju Volcanic Clusters", "AHA", "Clay"],
    image: getUnsplashImage(46, false),
    hoverImage: getUnsplashImage(46, true),
    description: "Mặt nạ đất sét hút dầu thừa, mụn cám mụn đầu đen và se khít lỗ chân lông cực tốt.",
    stock: 50,
  },
  {
    id: "lrp-effaclar-duo",
    name: "Kem Dưỡng Giảm Mụn Đầu Đen Ngừa Thâm Effaclar Duo+M",
    brand: "La Roche-Posay",
    category: "treatment",
    price: 485000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["oily", "combination", "sensitive"],
    concerns: ["acne", "dark_spots"],
    ingredients: ["Phylobioma", "Niacinamide", "LHA", "Procerad"],
    image: getUnsplashImage(47, false),
    hoverImage: getUnsplashImage(47, true),
    description: "Kem dưỡng chấm mụn giảm sưng viêm nhanh chóng, thông thoáng chân lông và ngăn hình thành thâm sẹo.",
    stock: 40,
  },
  {
    id: "banila-purifying",
    name: "Sáp Tẩy Trang Dành Cho Da Nhạy Cảm Clean It Zero Purifying",
    brand: "Banila Co",
    category: "treatment",
    price: 430000,
    rating: 4.8,
    reviews: 0,
    skinTypes: ["sensitive", "dry", "normal", "combination"],
    concerns: ["dehydration"],
    ingredients: ["Centella Extract", "Licorice Root Extract", "Green Tea Extract"],
    image: getUnsplashImage(48, false),
    hoverImage: getUnsplashImage(48, true),
    description: "Sáp tẩy trang chiết xuất từ rau má làm dịu da nhạy cảm mẩn đỏ khi tẩy trang.",
    stock: 30,
  },
  {
    id: "lrp-thermal-water",
    name: "Nước Xịt Khoáng Làm Dịu Chống Kích Ứng Da Thermal Spring Water",
    brand: "La Roche-Posay",
    category: "treatment",
    price: 395000,
    rating: 4.9,
    reviews: 0,
    skinTypes: ["sensitive", "dry", "normal", "combination", "oily"],
    concerns: ["dehydration"],
    ingredients: ["Selenium", "La Roche-Posay Thermal Water", "Minerals"],
    image: getUnsplashImage(49, false),
    hoverImage: getUnsplashImage(49, true),
    description: "Xịt khoáng thiên nhiên làm mát da, hạ nhiệt cháy nắng và làm dịu ngay lập tức các vết dị ứng.",
    stock: 55,
  }
];

const DEFAULT_REVIEWS = [
  {
    productId: "tfs-sun-cream",
    userName: "Khánh Linh",
    rating: 5,
    comment: "Kem chống nắng kiềm dầu cực tốt, nâng tone nhẹ nhàng tự nhiên. Không bị bí da.",
  },
  {
    productId: "tfs-nose-strips",
    userName: "Nguyễn Nam",
    rating: 5,
    comment: "Rửa mặt siêu sạch lỗ chân lông, hết sạch bã nhờn, da sờ sướng hẳn.",
  },
  {
    productId: "tfs-herb-day",
    userName: "Trần Hà",
    rating: 5,
    comment: "Sữa rửa mặt thơm mùi nha đam nhẹ dịu, rửa xong không khô da.",
  },
  {
    productId: "goodal-vit-c",
    userName: "Quỳnh Anh",
    rating: 5,
    comment: "Serum mờ thâm mụn siêu nhanh luôn, dùng tầm 2 tuần là thấy rõ sự khác biệt.",
  },
  {
    productId: "goodal-vit-c",
    userName: "Lê Hoa",
    rating: 4,
    comment: "Chất serum mát lạnh thấm nhanh, làm sáng da tốt nhưng cần kiên trì.",
  },
  {
    productId: "cetaphil-gentle",
    userName: "Huyền Trang",
    rating: 5,
    comment: "Sữa rửa mặt quốc dân cho da mụn nhạy cảm, vô cùng êm dịu.",
  },
  {
    productId: "lrp-baume-b5",
    userName: "Đức Anh",
    rating: 5,
    comment: "Phục hồi da tổn thương sau mụn rất tốt, baume chất hơi đặc nhưng xoa kỹ thấm êm.",
  },
  {
    productId: "loreal-micellar",
    userName: "Phạm Vy",
    rating: 5,
    comment: "Tẩy trang sạch sâu dịu nhẹ, không cay mắt, giá rẻ mà xài cực thích.",
  },
];

async function seedDatabase() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error("LỖI: MONGODB_URI không được thiết lập trong .env!");
    process.exit(1);
  }

  try {
    console.log("Đang kết nối tới MongoDB...");
    await mongoose.connect(uri);
    console.log("Kết nối MongoDB thành công!");

    // Clean existing data
    console.log("Đang xóa dữ liệu cũ...");
    await User.deleteMany({});
    await Product.deleteMany({});
    await Review.deleteMany({});
    console.log("Xóa dữ liệu cũ hoàn tất.");

    // Insert Default Users
    console.log("Đang đẩy danh sách tài khoản mẫu...");
    const createdUsers = await User.insertMany(DEFAULT_USERS);
    console.log(`Đã đẩy thành công ${createdUsers.length} tài khoản.`);

    // Insert Default Reviews
    console.log("Đang đẩy danh sách đánh giá mẫu...");
    const createdReviews = await Review.insertMany(DEFAULT_REVIEWS);
    console.log(`Đã đẩy thành công ${createdReviews.length} đánh giá.`);

    // Prepare products with calculated rating/reviews
    console.log("Đang tính toán điểm và số lượt đánh giá cho sản phẩm...");
    const productsToCreate = DEFAULT_PRODUCTS.map((prod) => {
      const prodReviews = DEFAULT_REVIEWS.filter((r) => r.productId === prod.id);
      const reviewsCount = prodReviews.length;
      let averageRating = prod.rating;
      let finalReviewsCount = prod.reviews;
      if (reviewsCount > 0) {
        const sum = prodReviews.reduce((acc, r) => acc + r.rating, 0);
        averageRating = Number((sum / reviewsCount).toFixed(1));
        finalReviewsCount = reviewsCount;
      }
      return {
        ...prod,
        rating: averageRating,
        reviews: finalReviewsCount,
      };
    });

    // Insert Default Products
    console.log("Đang đẩy danh sách sản phẩm mẫu...");
    const createdProducts = await Product.insertMany(productsToCreate);
    console.log(`Đã đẩy thành công ${createdProducts.length} sản phẩm.`);

    console.log("Hoàn tất quá trình seed dữ liệu thành công! 🎉");
    process.exit(0);
  } catch (error) {
    console.error("Đã xảy ra lỗi trong quá trình seed database:", error);
    process.exit(1);
  }
}

seedDatabase();
